#!/usr/bin/env osascript

-- a show help subroutine
on showMSG()
    set msg to "Use the following commands:\n"
    set msg to msg & "  mute               - Mute all Ads\n"
    set msg to msg & "  swap               - Swap ad with your local playlist instead of ads\n"
    set msg to msg & "  remove             - Play your local playlist like there's no ads at all\n"
    return msg
end showMSG

on run argv
  if count of argv is equal to 0 then
  	return showMSG()
  end if
  

  set state to "Music"
  set command to item 1 of argv
  using terms from application "Spotify"
    repeat while true

		  -- Set LastVolume
		  set lastVolume to 100
		  tell application "Spotify"
		  	if sound volume is not 0
		  		set lastVolume to sound volume
		  	end if
		  end tell

      if command is equal to "mute" then
	      tell application "Spotify"
          if ":ad:" is in spotify url of current track then
            set sound volume to 0
	  			else
            set sound volume to lastVolume 
          end if
      	end tell
      else if command is equal to "swap" then -- TODO fix pausing issue
      	tell application "Spotify"
          if ":ad:" is in spotify url of current track then
            set sound volume to 0
            Tell application "itunes" to play
	  			else
	  				Tell application "itunes" to pause
            set sound volume to lastVolume 
          end if
      	end tell
      else if command is equal to "remove" then -- TODO do somthing here :)
	      tell application "Spotify"
	          if ":ad:" is in spotify url of current track or state is equal to "Music" then
	            set sound volume to 0
	            set state to "Ad"
		  			else if state is equal to "Ad"
	            set sound volume to 100
	          end if
	      end tell
	    else 
	     return showMSG()
      end if
    end repeat
  end using terms from

end run
